---
pagetitle: "PPOL564 | Week 1 - Asynchronous lecture materials"
title:  <a href="http://ericdunford.com/ppol564/">Back to Course Website</a> <br><br><center> Choosing Your Poison <br> _Introductions, Installations, and IDEs_</center>
subtitle: <center> PPOL 564 | Data Science I | Foundations <br><br> Lecture Materials for Week 1 </center><br>
author: <center>Professor Eric Dunford (ed769@georgetown.edu) <br> McCourt School of Public Policy, Georgetown University<br><br> </center>
output: 
  html_document:
    includes: 
      after_body: async-footer.html
    css: async-page-style.css
    highlight: breezedark
    theme: flatly
    toc: true
---

<br><hr><br>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



# Learning Objectives 

<br>

- **Introduce the course**
  + What we'll cover in this course
  + Asynchronous and Synchronous Lectures
  + Assignments and expectations
  + How we'll communicate (Slack/Office Hours/class)
  + What we'll do if the pandemic gets bad again
    
    
- Using **Slack** & passing code

- Discuss all the things you need to **install** and how to do it. 

- Take a tour of the various **Integrated Development Environments** (IDE)s we'll come in contact with in this class.

  + Jupyter Notebooks
  + Atom + Hydrogen (which uses a Jupyter kernel for interactive evaluation)
  + RStudio + `reticulate`


- Using **Markdown** and **Latex** in Jupyter Notebooks and/or RMarkdown

- **`magic` commands** when using a Jupyter Kernel (Jupyter Notebook/Atom + Hydrogen)

- Cover some **commandline basics**

<br>



<br><hr><br>


# Installations {.tabset .tabset-pills}


<br>

Throughout the semester, I will use the commandline and many different IDEs when coding in Python or using Git. Here is an overview of these tools with instructions on how to install them. (These materials are also on the main course website).

<br>

## _

<br>
<hr>
<br>


## Commandline

<br>

At times, we'll use a unix-based commandline. The commandline will feature into our discussion on using `git` and also running Python programs. If you use a Mac or a Linux operating system, then a functioning commandline comes with your operating system. For Apple machines, this is the **Terminal**. 

For Windows (specifically Windows 10), you can enable Linux Bash shell. The following offers a [tutorial](https://www.howtogeek.com/249966/how-to-install-and-use-the-linux-bash-shell-on-windows-10/) on how to do this. If you're using a version of Windows that pre-dates version 10, then [Git Bash](https://www.atlassian.com/git/tutorials/git-bash#:~:text=Git%20Bash%20is%20an%20application,operating%20system%20through%20written%20commands.) offers a program will allow you to use `git` commands from your windows machine. 

Finally, you'll notice that my terminal will have a slightly different look than the one on your machine. This is because I'm using ["Oh My Zsh"](https://ohmyz.sh/) which is open-source software that allows me to customize my commandline. The above link offers everything you'd need to installing Oh My Zsh on your machine. 

<br>
<hr>
<br>

## Python3 

<br>

We'll use Python3 throughout this course. Below are instructions for downloading Python3 using commandline packages manager (`Homebrew` for mac, `Chocolatey` for windows). 

<br>

- [Installing Python3 using Homebrew on a Mac (Apple)](https://docs.python-guide.org/starting/install3/osx/)

- [Installing Python3 using Chocolatey on a PC (Windows)](https://python-docs.readthedocs.io/en/latest/starting/install3/win.html)

<br>

An alternative way to install Python3 is to download an [**Anaconda** distribution](https://www.anaconda.com/products/individual). The instructor will use `pip` rather than `conda` in the instruction for downloading Python modules. These are simply two ways of downloading and managing open-source software packages. <u>Choose which ever works best for you</u>. 


<br>
<hr>
<br>

## Jupyter Notebook

<br> 

Once you have Python3 on your computer, you can install a Jupyter Notebook. If you downloaded Python3 using Anaconda, then Jupyter Notebook comes with the distribution and requires no further installation on your part. If you install Python3 using `Homebrew`/`Chocolately`, you can install Jupyter notebook running the following code using your commandline.

```{bash,eval=F}
pip install notebook
```
You can then activate a Jupyter Notebook from the commandline by typing:

```{bash,eval=F}
jupyter notebook
```

If you've installed Python using Anaconda, the distribution provides a click-able icon to fire up a Jupyter Notebook. The advantage of using the commandline, however, is that you can set the working directory prior to firing up a notebook. This will allow you to work within a specific project folder more easily. 

<br>
<hr>
<br>

## Atom + `hydrogen`

<br>

[**Atom**](https://atom.io/) is a hack-able text editor built by Github. The following are [instruction on how to install Atom](https://flight-manual.atom.io/getting-started/sections/installing-atom/) on your machine. 

Atom allows you to install open-source packages that provide additional functionality. The following packages will help you as you use Atom to program in Python. Of these, [`Hydrogen`](https://atom.io/packages/hydrogen) is the most important. It'll allow you to use a Jupyter kernel from within Atom to evaluate code.

```{bash,eval=F}
├── Hydrogen@2.14.4
├── atom-beautify@0.33.4
├── atom-language-r@1.4.8
├── atom-material-syntax@1.0.8
├── atom-material-syntax-light@0.4.6
├── atom-material-ui@2.1.3
├── auto-update-packages@1.0.1
├── autocomplete-R@0.6.0
├── autocomplete-modules@2.3.0
├── autocomplete-python@1.16.0
├── color-picker@2.3.0
├── docblock-python@0.19.0
├── file-icons@2.1.42
├── fix-indent-on-paste@0.1.1
├── fold-comments@0.6.0
├── git-log@0.4.1
├── hey-pane@1.2.0
├── hydrogen-cell-separator@0.4.1
├── language-weave@0.7.2
├── minimap@4.29.9
├── pdf-view@0.72.0
├── platformio-ide-terminal@2.10.0
├── python-indent@1.2.6
├── reindent@1.5.0
├── simple-drag-drop-text@0.5.0
├── symbols-tree-view@0.14.0
└── wordcount@3.2.0
```

To install any one of these packages from the commandline, type:
```{bash,eval = F}
# apm == "Atom package manager"
apm install <package-name>
```

There is also a dedicated package manager built into Atom which you can use to download and install new packages. Open Atom then `Settings > Install` and type the package name. 

<br>
<hr>
<br>

## RStudio + `reticulate`

<br>

In your classes that are focused on using `R`, `RStudio` will be your main IDE. However, `RStudio` isn't just for `R`. It can handle a number of different languages. We'll Python in `RStudio` using the `reticulate` package. We'll talk about some of the advantages for doing this in class, but for now, let's cover installation.

To install `RStudio`, [download from the following link](https://www.rstudio.com/products/rstudio/download/) (make sure to scroll all the way to the bottom).

`reticulate` is an R package that allows one run a Python REPL in the R console. In addition, it allows one to read in and use Python code, and pass data between R and and Python. The following provides [instructions on installing `reticulate`](https://rstudio.github.io/reticulate/).

**Note**: If you have multiple versions of Python on your computer, reticulate can get confused with regard to which version it is referencing. The [following article](https://rstudio.github.io/reticulate/articles/versions.html) covers these issues. The best way to resolve this issue is by creating a `.Rprofile` file that sends instructions regarding the specific version of Python you wish to use. 

> "By setting the value of the RETICULATE_PYTHON environment variable to a Python binary. Note that if you set this environment variable, then the specified version of Python will always be used (i.e. this is prescriptive rather than advisory). To set the value of RETICULATE_PYTHON, insert Sys.setenv(RETICULATE_PYTHON = PATH) into your project’s .Rprofile, where PATH is your preferred Python binary."
 


<br>
<hr>
<br>

## Other Software

<br>

Here is an overview of other text editors that are popular for programming in Python, which you won't see featured in this course. Note I'm agnostic on whatever you use to learn Python and some find that different set ups work better for them. If one of these setups works better for you, I encourage you to use it (and tell me about how it went)!

<br>

- [Sublime Text](https://www.sublimetext.com/)
- [PyCharm](https://www.jetbrains.com/pycharm/)
- [Spyder](https://www.spyder-ide.org/)
- [Rodeo](https://rodeo.yhat.com/)
- [Visual Studio](https://code.visualstudio.com/docs/languages/python)

<br>
<hr>
<br>

# Markdown + $\LaTeX$

<br>

## Markdown 

One of the primary advantages of using notebooks (Jupyter and RMarkdown) when writing code is that we can mix code with prose (text). That is, we can put the code side-by-side with the analysis, combining both analytics with insight.  

[Markdown](https://www.markdownguide.org) offers a lightweight language for formatting text. The following [cheatsheet](https://www.markdownguide.org/cheat-sheet/) provides a useful guide of various Markdown commands. 

Try rendering Markdown code in a Jupyter Notebook and/or RMarkdown (`.rmd`).

<br>

## $\LaTeX$

[$\LaTeX$](https://www.latex-project.org/about/) ("Lah-Tec") is a "document preparation system for high-quality typesetting. It is most often used for medium-to-large technical or scientific documents but it can be used for almost any form of publishing." At it's best LaTeX allows for complete customization of a document from scratch. In practice, this usually means "typing pretty math equations". At it's worst LaTeX is convoluted and fine way to waste one's time. 

We'll use LaTeX to write and render mathematical formulas. LaTeX plays well with markdown, making it easy to write text, code, _and math_! This will be useful when we need to be technical. 

LaTeX math has it's own syntax that can be hard to use when first starting out. You'll get used to it as we see it pop up throughout the program. 

<br>

**Example 1**: Math equation inline with some text. Note the `$$` single dollar signs. 

```{latex}
This is my model $y_i = \beta_0 + \beta_1 x_i + \epsilon_i$.
```

**Result**:

> This is my model $y_i = \beta_0 + \beta_1 x_i + \epsilon$.

<br>

**Example 2**: A stand along math equation. Note the double dollar signs.

```{latex}
$$ pr(y_i = 1) = \frac{1}{1 + e^{\beta_0 + \beta_1 x_i}}$$
```

**Result**:

> $$ pr(y_i = 1) = \frac{1}{1 + e^{\beta_0 + \beta_1 x_i}}$$

<br> 


We'be provided some resources in this week's supplemental [readings](https://docx2latex.com/tutorials/Mathematical-equations-LaTeX.html) to help you navigate the labyrinth that is LaTeX.

<br>
<hr>
<br>

# Jupyter `magic` Commands

<br>

Magic commands are special commands that can be executed in a Jupyter code cell (so these commands will be relevant if you're in a Jupyter Notebook or using Atom + Hydrogen). Magic commands are prefixed by the `%` character. These magic commands are designed to succinctly solve various common problems in standard data analysis.

Magic commands come in two flavors:

- **line magics**, which are denoted by a single `%` prefix and operate on a single line of input,
- **cell magics**, which are denoted by a double `%%` prefix and operate on multiple lines of input.

Here is a [short Jupyter Notebook](using-jupyter-notebooks.html) that walks through some useful magic commands. In addition, it also provides guidance on **Notebook Extensions** to add functionality to a Jupyter Notebook. 


<br>
<hr>
<br>

# Commandline Basics

<br>

The following outlines a few common commands that will be useful as you move forward. Disclaimer: some of these commands may differ given your operating system, but it's only quick Google search to find out how things are done on your machine.

- `pwd`: check working directory
- `cd <path>`: change working directory
    + `cd ..`: go back to the last directory
    + `cd  `: go to the top directory
    + `cd -`: go back to where you once where
- `ls`: list all files in the working directory
- `mkdir <dir name>`: make a directory
- `mv <old path> <new path>`: move file from old path to new path
- `cp <old path> <new path>`: copy file from old path to new path
- `ctr + c`: stops current execution.
- `cat <file>`: print the entire file
- `head`: view the start of a file to some $N$ number of lines
    - `head -n 3 file`
- `tail`: view the end of a file to some $N$ number of lines
    - `tail -n 3 file`

- Making a file:
    - `touch <file name>`
    - `echo 'text' > file`
        
- Renaming a File:
    - `mv <old file name> <new file name>`
    
- Asking for help:
    - `man <command name>`
    - `<command name> -h`
    
<br>